//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysModule
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int ParentID { get; set; }
        public string ControlName { get; set; }
        public string ActionName { get; set; }
        public string IConName { get; set; }
        public int OrderID { get; set; }
        public string AreaName { get; set; }
        public bool State { get; set; }
        public string Modal { get; set; }
        public Nullable<int> FormMethod { get; set; }
        public bool IsStop { get; set; }
    }
}
