//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUserRole
    {
        public int ID { get; set; }
        public int SysUserId { get; set; }
        public int SysRoleId { get; set; }
    
        public virtual SysRole SysRole { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
